import { IIcon } from '../interfaces';

export const VALUE_CATEGORIES: IIcon[] = [
  { icon: 'pets', name: 'Pets', value: 'pets' },
  { icon: 'android', name: 'Android', value: 'android' },
  { icon: 'book', name: 'Book', value: 'book' },
  { icon: 'handyman', name: 'Handyman', value: 'handyman' },
  { icon: 'eco', name: 'Eco', value: 'eco' },
  { icon: 'favorite', name: 'Favorite', value: 'favorite' },
  { icon: 'schedule', name: 'Schedule', value: 'schedule' },
  { icon: 'shopping_cart', name: 'Shopping cart', value: 'shopping_cart' },
  { icon: 'store', name: 'Store', value: 'store' },
  { icon: 'flight', name: 'Flight', value: 'flight' },
  { icon: 'language', name: 'Language', value: 'language' },
  { icon: 'commute', name: 'Commute', value: 'commute' },
  { icon: 'explore', name: 'Explore', value: 'explore' },
  { icon: 'help', name: 'Help', value: 'help' },
  { icon: 'supervised_user_circle', name: 'Users', value: 'supervised_user_circle' },
  { icon: 'verified_user', name: 'Verified', value: 'verified_user' },
  { icon: 'work', name: 'Work', value: 'work' },
  { icon: 'games', name: 'Games', value: 'games' },
  { icon: 'movie', name: 'Movie', value: 'movie' },
  { icon: 'headset', name: 'Headset', value: 'headset' },
  { icon: 'web', name: 'Web', value: 'web' },
  { icon: 'speed', name: 'Speed', value: 'speed' },
  { icon: 'phone', name: 'Phone', value: 'phone' },
  { icon: 'navigation', name: 'Navigation', value: 'navigation' },
  { icon: 'lock', name: 'Lock', value: 'lock' },
  { icon: 'weekend', name: 'Weekend', value: 'weekend' },
  { icon: 'image', name: 'Image', value: 'image' },
  { icon: 'cloud', name: 'Cloud', value: 'cloud' },
  { icon: 'laptop_mac', name: 'Laptop Mac', value: 'laptop_mac' },
  { icon: 'smartphone', name: 'Smartphone', value: 'smartphone' },
  { icon: 'watch', name: 'Watch', value: 'watch' },
  { icon: 'camera', name: 'Camera', value: 'camera' },
  { icon: 'bedtime', name: 'Bedtime', value: 'bedtime' },
  { icon: 'nature', name: 'Nature', value: 'nature' },
  { icon: 'palette', name: 'palette', value: 'palette' },
  { icon: 'fastfood', name: 'Fast food', value: 'fastfood' },
  { icon: 'local_cafe', name: 'Local cafe', value: 'local_cafe' },
  { icon: 'local_bar', name: 'Local bar', value: 'local_bar' },
  { icon: 'place', name: 'Place', value: 'place' },
  { icon: 'hotel', name: 'Hotel', value: 'hotel' },
  { icon: 'pedal_bike', name: 'Pedal bike', value: 'pedal_bike' },
  { icon: 'restaurant', name: 'Restaurant', value: 'restaurant' },
  { icon: 'terrain', name: 'Terrain', value: 'terrain' },
  { icon: 'wifi', name: 'Wifi', value: 'wifi' },
  { icon: 'backpack', name: 'Backpack', value: 'backpack' },
  { icon: 'sports_motorsports', name: 'Motorsports', value: 'sports_motorsports' }
];
